### PR TITLE
clarified VectorNormal and fixed #39 in the process

### LINKED ISSUE #39: VectorNormal (Pascal) crashes when passed a zero vector
Here, try it:

```
program VectorNormalCrashTest;
uses SwinGame, sgTypes;
begin
  VectorNormal(VectorTo(0, 0));
end.
```

```
EInvalidOp: Invalid floating point operation
```

The cause is fairly obvious: [`VectorNormal` is dividing by the magnitude](https://github.com/macite/swingame/blob/f15efcc096a3d641565e61bd4727be99673b3e8a/CoreSDK/src/sgGeometry.pas#L1989) (the variable isn't helpfully named, either). This would be less of a hassle if I was calling `VectorNormal` directly. Unfortunately, I'm not - it's happening from `CollideCircleLine`, and refactoring my code to avoid that would be a lot of trouble.

### PR DESCRIPTION
**Pull request by michaelb958**
Dividing by zero is bad. Also, there's a perfectly good magnitude
function.

### CODE REVIEW

**Comment by macite** [comment]
Not sure this is the best solution, as a vector with no magnitude does not have a normal.
A better solution would be to alter the circle collision so that it avoids asking for this when the sprite has no velocity.

**Comment by michaelb958** [comment]
It doesn't feel particularly right for $PROGRAM to bomb out with a floating-point exception when all $PROGRAMMER did was pass in a vector; SwinGame is meant to be at a higher level of abstraction.

**Comment by jgardner8** [comment]
I think when Andrew says "the circle collision" he doesn't mean your game code, but the CollideCircleLine function you had this issue with, and whatever other circle collision functions there are. 

The problem is not that VectorNormal crashes on a vector of 0 magnitude -- that is exactly what should happen as the function has no valid result. However it doesn't make sense for the circle collision functions to crash if the sprite isn't moving, so the fix should be at that level.

**Comment by macite** [comment]
I've updated this so it returns a null/zero vector and raises a warning, and have also updated the collision code so that it avoids calling VectorNormal when there is no velocity.

**Comment by michaelb958** [comment]
I approve of 0dc6c9c1ab55147fb9f685d141b918b6b1517607, for what it's worth.

**Pull request closed without merging**
